import {
  ATENDIMENTO_ATIVO_EXISTENTE_MESSAGE,
  ATENDIMENTO_NAO_ESTA_FINALIZANDO_MESSAGE,
  ATIVIDADES_NAO_INICIADAS_MESSAGE,
  CHECKLIST_INCOMPLETO_MESSAGE,
  CHECKLIST_INDISPONIVEL_MESSAGE,
  CONFIRMACAO_FORA_DE_ORDEM_NECESSARIA_MESSAGE,
  DETALHE_OBRIGATORIO_MESSAGE,
  EM_ATENDIMENTO_NAO_PODE_SAIR_MESSAGE,
  FUNCIONARIO_ALVO_INDISPONIVEL_MESSAGE,
  FUNCIONARIO_ALVO_INVALIDO_MESSAGE,
  FUNCIONARIO_EM_ATENDIMENTO_MESSAGE,
  JA_FORA_DA_LISTA_MESSAGE,
  JA_NA_LISTA_MESSAGE,
  MOTIVO_INVALIDO_MESSAGE,
  MOTIVO_OBRIGATORIO_MESSAGE,
  NENHUM_ATENDIMENTO_ATIVO_MESSAGE,
  NENHUM_CLIENTE_INFORMADO_MESSAGE,
  PRAZO_PROVISORIO_EXPIRADO_MESSAGE,
  SEM_PERMISSAO_CANCELAR_MESSAGE,
  SEM_PERMISSAO_REMOVER_MESSAGE,
} from "@/config/constants";

const ATENDIMENTO_ERROR_SQLSTATE = "P0001";

const KNOWN_ERROR_MESSAGES: Record<string, string> = {
  ATIVIDADES_NAO_INICIADAS: ATIVIDADES_NAO_INICIADAS_MESSAGE,
  ATENDIMENTO_ATIVO_EXISTENTE: ATENDIMENTO_ATIVO_EXISTENTE_MESSAGE,
  CONFIRMACAO_FORA_DE_ORDEM_NECESSARIA: CONFIRMACAO_FORA_DE_ORDEM_NECESSARIA_MESSAGE,
  NENHUM_ATENDIMENTO_ATIVO: NENHUM_ATENDIMENTO_ATIVO_MESSAGE,
  PRAZO_PROVISORIO_EXPIRADO: PRAZO_PROVISORIO_EXPIRADO_MESSAGE,
  NENHUM_CLIENTE_INFORMADO: NENHUM_CLIENTE_INFORMADO_MESSAGE,
  ATENDIMENTO_NAO_ESTA_FINALIZANDO: ATENDIMENTO_NAO_ESTA_FINALIZANDO_MESSAGE,
  MOTIVO_OBRIGATORIO: MOTIVO_OBRIGATORIO_MESSAGE,
  MOTIVO_INVALIDO: MOTIVO_INVALIDO_MESSAGE,
  DETALHE_OBRIGATORIO: DETALHE_OBRIGATORIO_MESSAGE,
  FUNCIONARIO_ALVO_INVALIDO: FUNCIONARIO_ALVO_INVALIDO_MESSAGE,
  FUNCIONARIO_ALVO_INDISPONIVEL: FUNCIONARIO_ALVO_INDISPONIVEL_MESSAGE,
  SEM_PERMISSAO_CANCELAR: SEM_PERMISSAO_CANCELAR_MESSAGE,
  JA_FORA_DA_LISTA: JA_FORA_DA_LISTA_MESSAGE,
  JA_NA_LISTA: JA_NA_LISTA_MESSAGE,
  EM_ATENDIMENTO_NAO_PODE_SAIR: EM_ATENDIMENTO_NAO_PODE_SAIR_MESSAGE,
  FUNCIONARIO_EM_ATENDIMENTO: FUNCIONARIO_EM_ATENDIMENTO_MESSAGE,
  SEM_PERMISSAO_REMOVER: SEM_PERMISSAO_REMOVER_MESSAGE,
  CHECKLIST_INCOMPLETO: CHECKLIST_INCOMPLETO_MESSAGE,
  CHECKLIST_INDISPONIVEL: CHECKLIST_INDISPONIVEL_MESSAGE,
};

/**
 * Distinguishes the Atendimento RPCs' known business-rule error codes
 * (raised via `raise exception using errcode = 'P0001', message = '...'`,
 * same convention as isInvalidSessionError) from ordinary network errors or
 * INVALID_SESSION, which callers must handle separately.
 */
function getAtendimentoErrorCode(error: unknown): string | null {
  if (!error || typeof error !== "object") return null;
  const candidate = error as { message?: unknown; code?: unknown };
  if (candidate.code !== ATENDIMENTO_ERROR_SQLSTATE || typeof candidate.message !== "string") {
    return null;
  }
  return candidate.message;
}

export function isForaDeOrdemConfirmationRequired(error: unknown): boolean {
  return getAtendimentoErrorCode(error) === "CONFIRMACAO_FORA_DE_ORDEM_NECESSARIA";
}

export function getAtendimentoErrorMessage(error: unknown): string | null {
  const code = getAtendimentoErrorCode(error);
  if (code === null) return null;
  return KNOWN_ERROR_MESSAGES[code] ?? null;
}
