/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperacoesIndexRouteImport } from './routes/operacoes/index'
import { Route as ConhecimentoCulturaIndexRouteImport } from './routes/conhecimento-cultura/index'
import { Route as AdministrativoIndexRouteImport } from './routes/administrativo/index'
import { Route as OperacoesMensagensWhatsappRouteImport } from './routes/operacoes/mensagens-whatsapp'
import { Route as OperacoesLinksImportantesRouteImport } from './routes/operacoes/links-importantes'
import { Route as OperacoesLimpezaRouteImport } from './routes/operacoes/limpeza'
import { Route as OperacoesEscalaRouteImport } from './routes/operacoes/escala'
import { Route as OperacoesContagemEmbalagensRouteImport } from './routes/operacoes/contagem-embalagens'
import { Route as ConhecimentoCulturaTamanhosCalcadosRouteImport } from './routes/conhecimento-cultura/tamanhos-calcados'
import { Route as ConhecimentoCulturaPrincipiosRouteImport } from './routes/conhecimento-cultura/principios'
import { Route as AdministrativoTermosBuscaRouteImport } from './routes/administrativo/termos-busca'
import { Route as AdministrativoEscalaRouteImport } from './routes/administrativo/escala'
import { Route as AdministrativoAtendimentoRouteImport } from './routes/administrativo/atendimento'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesIndexRoute = OperacoesIndexRouteImport.update({
  id: '/operacoes/',
  path: '/operacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoCulturaIndexRoute =
  ConhecimentoCulturaIndexRouteImport.update({
    id: '/conhecimento-cultura/',
    path: '/conhecimento-cultura/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrativoIndexRoute = AdministrativoIndexRouteImport.update({
  id: '/administrativo/',
  path: '/administrativo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesMensagensWhatsappRoute =
  OperacoesMensagensWhatsappRouteImport.update({
    id: '/operacoes/mensagens-whatsapp',
    path: '/operacoes/mensagens-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperacoesLinksImportantesRoute =
  OperacoesLinksImportantesRouteImport.update({
    id: '/operacoes/links-importantes',
    path: '/operacoes/links-importantes',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperacoesLimpezaRoute = OperacoesLimpezaRouteImport.update({
  id: '/operacoes/limpeza',
  path: '/operacoes/limpeza',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesEscalaRoute = OperacoesEscalaRouteImport.update({
  id: '/operacoes/escala',
  path: '/operacoes/escala',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesContagemEmbalagensRoute =
  OperacoesContagemEmbalagensRouteImport.update({
    id: '/operacoes/contagem-embalagens',
    path: '/operacoes/contagem-embalagens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConhecimentoCulturaTamanhosCalcadosRoute =
  ConhecimentoCulturaTamanhosCalcadosRouteImport.update({
    id: '/conhecimento-cultura/tamanhos-calcados',
    path: '/conhecimento-cultura/tamanhos-calcados',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConhecimentoCulturaPrincipiosRoute =
  ConhecimentoCulturaPrincipiosRouteImport.update({
    id: '/conhecimento-cultura/principios',
    path: '/conhecimento-cultura/principios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrativoTermosBuscaRoute =
  AdministrativoTermosBuscaRouteImport.update({
    id: '/administrativo/termos-busca',
    path: '/administrativo/termos-busca',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrativoEscalaRoute = AdministrativoEscalaRouteImport.update({
  id: '/administrativo/escala',
  path: '/administrativo/escala',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativoAtendimentoRoute =
  AdministrativoAtendimentoRouteImport.update({
    id: '/administrativo/atendimento',
    path: '/administrativo/atendimento',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/termos': typeof TermosRoute
  '/administrativo/atendimento': typeof AdministrativoAtendimentoRoute
  '/administrativo/escala': typeof AdministrativoEscalaRoute
  '/administrativo/termos-busca': typeof AdministrativoTermosBuscaRoute
  '/conhecimento-cultura/principios': typeof ConhecimentoCulturaPrincipiosRoute
  '/conhecimento-cultura/tamanhos-calcados': typeof ConhecimentoCulturaTamanhosCalcadosRoute
  '/operacoes/contagem-embalagens': typeof OperacoesContagemEmbalagensRoute
  '/operacoes/escala': typeof OperacoesEscalaRoute
  '/operacoes/limpeza': typeof OperacoesLimpezaRoute
  '/operacoes/links-importantes': typeof OperacoesLinksImportantesRoute
  '/operacoes/mensagens-whatsapp': typeof OperacoesMensagensWhatsappRoute
  '/administrativo/': typeof AdministrativoIndexRoute
  '/conhecimento-cultura/': typeof ConhecimentoCulturaIndexRoute
  '/operacoes/': typeof OperacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/termos': typeof TermosRoute
  '/administrativo/atendimento': typeof AdministrativoAtendimentoRoute
  '/administrativo/escala': typeof AdministrativoEscalaRoute
  '/administrativo/termos-busca': typeof AdministrativoTermosBuscaRoute
  '/conhecimento-cultura/principios': typeof ConhecimentoCulturaPrincipiosRoute
  '/conhecimento-cultura/tamanhos-calcados': typeof ConhecimentoCulturaTamanhosCalcadosRoute
  '/operacoes/contagem-embalagens': typeof OperacoesContagemEmbalagensRoute
  '/operacoes/escala': typeof OperacoesEscalaRoute
  '/operacoes/limpeza': typeof OperacoesLimpezaRoute
  '/operacoes/links-importantes': typeof OperacoesLinksImportantesRoute
  '/operacoes/mensagens-whatsapp': typeof OperacoesMensagensWhatsappRoute
  '/administrativo': typeof AdministrativoIndexRoute
  '/conhecimento-cultura': typeof ConhecimentoCulturaIndexRoute
  '/operacoes': typeof OperacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/termos': typeof TermosRoute
  '/administrativo/atendimento': typeof AdministrativoAtendimentoRoute
  '/administrativo/escala': typeof AdministrativoEscalaRoute
  '/administrativo/termos-busca': typeof AdministrativoTermosBuscaRoute
  '/conhecimento-cultura/principios': typeof ConhecimentoCulturaPrincipiosRoute
  '/conhecimento-cultura/tamanhos-calcados': typeof ConhecimentoCulturaTamanhosCalcadosRoute
  '/operacoes/contagem-embalagens': typeof OperacoesContagemEmbalagensRoute
  '/operacoes/escala': typeof OperacoesEscalaRoute
  '/operacoes/limpeza': typeof OperacoesLimpezaRoute
  '/operacoes/links-importantes': typeof OperacoesLinksImportantesRoute
  '/operacoes/mensagens-whatsapp': typeof OperacoesMensagensWhatsappRoute
  '/administrativo/': typeof AdministrativoIndexRoute
  '/conhecimento-cultura/': typeof ConhecimentoCulturaIndexRoute
  '/operacoes/': typeof OperacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimento'
    | '/dashboard'
    | '/estoque'
    | '/termos'
    | '/administrativo/atendimento'
    | '/administrativo/escala'
    | '/administrativo/termos-busca'
    | '/conhecimento-cultura/principios'
    | '/conhecimento-cultura/tamanhos-calcados'
    | '/operacoes/contagem-embalagens'
    | '/operacoes/escala'
    | '/operacoes/limpeza'
    | '/operacoes/links-importantes'
    | '/operacoes/mensagens-whatsapp'
    | '/administrativo/'
    | '/conhecimento-cultura/'
    | '/operacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimento'
    | '/dashboard'
    | '/estoque'
    | '/termos'
    | '/administrativo/atendimento'
    | '/administrativo/escala'
    | '/administrativo/termos-busca'
    | '/conhecimento-cultura/principios'
    | '/conhecimento-cultura/tamanhos-calcados'
    | '/operacoes/contagem-embalagens'
    | '/operacoes/escala'
    | '/operacoes/limpeza'
    | '/operacoes/links-importantes'
    | '/operacoes/mensagens-whatsapp'
    | '/administrativo'
    | '/conhecimento-cultura'
    | '/operacoes'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/dashboard'
    | '/estoque'
    | '/termos'
    | '/administrativo/atendimento'
    | '/administrativo/escala'
    | '/administrativo/termos-busca'
    | '/conhecimento-cultura/principios'
    | '/conhecimento-cultura/tamanhos-calcados'
    | '/operacoes/contagem-embalagens'
    | '/operacoes/escala'
    | '/operacoes/limpeza'
    | '/operacoes/links-importantes'
    | '/operacoes/mensagens-whatsapp'
    | '/administrativo/'
    | '/conhecimento-cultura/'
    | '/operacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRoute
  TermosRoute: typeof TermosRoute
  AdministrativoAtendimentoRoute: typeof AdministrativoAtendimentoRoute
  AdministrativoEscalaRoute: typeof AdministrativoEscalaRoute
  AdministrativoTermosBuscaRoute: typeof AdministrativoTermosBuscaRoute
  ConhecimentoCulturaPrincipiosRoute: typeof ConhecimentoCulturaPrincipiosRoute
  ConhecimentoCulturaTamanhosCalcadosRoute: typeof ConhecimentoCulturaTamanhosCalcadosRoute
  OperacoesContagemEmbalagensRoute: typeof OperacoesContagemEmbalagensRoute
  OperacoesEscalaRoute: typeof OperacoesEscalaRoute
  OperacoesLimpezaRoute: typeof OperacoesLimpezaRoute
  OperacoesLinksImportantesRoute: typeof OperacoesLinksImportantesRoute
  OperacoesMensagensWhatsappRoute: typeof OperacoesMensagensWhatsappRoute
  AdministrativoIndexRoute: typeof AdministrativoIndexRoute
  ConhecimentoCulturaIndexRoute: typeof ConhecimentoCulturaIndexRoute
  OperacoesIndexRoute: typeof OperacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/': {
      id: '/operacoes/'
      path: '/operacoes'
      fullPath: '/operacoes/'
      preLoaderRoute: typeof OperacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento-cultura/': {
      id: '/conhecimento-cultura/'
      path: '/conhecimento-cultura'
      fullPath: '/conhecimento-cultura/'
      preLoaderRoute: typeof ConhecimentoCulturaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativo/': {
      id: '/administrativo/'
      path: '/administrativo'
      fullPath: '/administrativo/'
      preLoaderRoute: typeof AdministrativoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/mensagens-whatsapp': {
      id: '/operacoes/mensagens-whatsapp'
      path: '/operacoes/mensagens-whatsapp'
      fullPath: '/operacoes/mensagens-whatsapp'
      preLoaderRoute: typeof OperacoesMensagensWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/links-importantes': {
      id: '/operacoes/links-importantes'
      path: '/operacoes/links-importantes'
      fullPath: '/operacoes/links-importantes'
      preLoaderRoute: typeof OperacoesLinksImportantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/limpeza': {
      id: '/operacoes/limpeza'
      path: '/operacoes/limpeza'
      fullPath: '/operacoes/limpeza'
      preLoaderRoute: typeof OperacoesLimpezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/escala': {
      id: '/operacoes/escala'
      path: '/operacoes/escala'
      fullPath: '/operacoes/escala'
      preLoaderRoute: typeof OperacoesEscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/contagem-embalagens': {
      id: '/operacoes/contagem-embalagens'
      path: '/operacoes/contagem-embalagens'
      fullPath: '/operacoes/contagem-embalagens'
      preLoaderRoute: typeof OperacoesContagemEmbalagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento-cultura/tamanhos-calcados': {
      id: '/conhecimento-cultura/tamanhos-calcados'
      path: '/conhecimento-cultura/tamanhos-calcados'
      fullPath: '/conhecimento-cultura/tamanhos-calcados'
      preLoaderRoute: typeof ConhecimentoCulturaTamanhosCalcadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento-cultura/principios': {
      id: '/conhecimento-cultura/principios'
      path: '/conhecimento-cultura/principios'
      fullPath: '/conhecimento-cultura/principios'
      preLoaderRoute: typeof ConhecimentoCulturaPrincipiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativo/termos-busca': {
      id: '/administrativo/termos-busca'
      path: '/administrativo/termos-busca'
      fullPath: '/administrativo/termos-busca'
      preLoaderRoute: typeof AdministrativoTermosBuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativo/escala': {
      id: '/administrativo/escala'
      path: '/administrativo/escala'
      fullPath: '/administrativo/escala'
      preLoaderRoute: typeof AdministrativoEscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativo/atendimento': {
      id: '/administrativo/atendimento'
      path: '/administrativo/atendimento'
      fullPath: '/administrativo/atendimento'
      preLoaderRoute: typeof AdministrativoAtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRoute,
  TermosRoute: TermosRoute,
  AdministrativoAtendimentoRoute: AdministrativoAtendimentoRoute,
  AdministrativoEscalaRoute: AdministrativoEscalaRoute,
  AdministrativoTermosBuscaRoute: AdministrativoTermosBuscaRoute,
  ConhecimentoCulturaPrincipiosRoute: ConhecimentoCulturaPrincipiosRoute,
  ConhecimentoCulturaTamanhosCalcadosRoute:
    ConhecimentoCulturaTamanhosCalcadosRoute,
  OperacoesContagemEmbalagensRoute: OperacoesContagemEmbalagensRoute,
  OperacoesEscalaRoute: OperacoesEscalaRoute,
  OperacoesLimpezaRoute: OperacoesLimpezaRoute,
  OperacoesLinksImportantesRoute: OperacoesLinksImportantesRoute,
  OperacoesMensagensWhatsappRoute: OperacoesMensagensWhatsappRoute,
  AdministrativoIndexRoute: AdministrativoIndexRoute,
  ConhecimentoCulturaIndexRoute: ConhecimentoCulturaIndexRoute,
  OperacoesIndexRoute: OperacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
