/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AdministrativoRouteImport } from './routes/administrativo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperacoesIndexRouteImport } from './routes/operacoes/index'
import { Route as ConhecimentoCulturaIndexRouteImport } from './routes/conhecimento-cultura/index'
import { Route as OperacoesMensagensWhatsappRouteImport } from './routes/operacoes/mensagens-whatsapp'
import { Route as OperacoesLinksImportantesRouteImport } from './routes/operacoes/links-importantes'
import { Route as OperacoesEscalaRouteImport } from './routes/operacoes/escala'
import { Route as OperacoesContagemEmbalagensRouteImport } from './routes/operacoes/contagem-embalagens'
import { Route as ConhecimentoCulturaPrincipiosRouteImport } from './routes/conhecimento-cultura/principios'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativoRoute = AdministrativoRouteImport.update({
  id: '/administrativo',
  path: '/administrativo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesIndexRoute = OperacoesIndexRouteImport.update({
  id: '/operacoes/',
  path: '/operacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoCulturaIndexRoute =
  ConhecimentoCulturaIndexRouteImport.update({
    id: '/conhecimento-cultura/',
    path: '/conhecimento-cultura/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperacoesMensagensWhatsappRoute =
  OperacoesMensagensWhatsappRouteImport.update({
    id: '/operacoes/mensagens-whatsapp',
    path: '/operacoes/mensagens-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperacoesLinksImportantesRoute =
  OperacoesLinksImportantesRouteImport.update({
    id: '/operacoes/links-importantes',
    path: '/operacoes/links-importantes',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperacoesEscalaRoute = OperacoesEscalaRouteImport.update({
  id: '/operacoes/escala',
  path: '/operacoes/escala',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesContagemEmbalagensRoute =
  OperacoesContagemEmbalagensRouteImport.update({
    id: '/operacoes/contagem-embalagens',
    path: '/operacoes/contagem-embalagens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConhecimentoCulturaPrincipiosRoute =
  ConhecimentoCulturaPrincipiosRouteImport.update({
    id: '/conhecimento-cultura/principios',
    path: '/conhecimento-cultura/principios',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrativo': typeof AdministrativoRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/termos': typeof TermosRoute
  '/conhecimento-cultura/principios': typeof ConhecimentoCulturaPrincipiosRoute
  '/operacoes/contagem-embalagens': typeof OperacoesContagemEmbalagensRoute
  '/operacoes/escala': typeof OperacoesEscalaRoute
  '/operacoes/links-importantes': typeof OperacoesLinksImportantesRoute
  '/operacoes/mensagens-whatsapp': typeof OperacoesMensagensWhatsappRoute
  '/conhecimento-cultura/': typeof ConhecimentoCulturaIndexRoute
  '/operacoes/': typeof OperacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrativo': typeof AdministrativoRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/termos': typeof TermosRoute
  '/conhecimento-cultura/principios': typeof ConhecimentoCulturaPrincipiosRoute
  '/operacoes/contagem-embalagens': typeof OperacoesContagemEmbalagensRoute
  '/operacoes/escala': typeof OperacoesEscalaRoute
  '/operacoes/links-importantes': typeof OperacoesLinksImportantesRoute
  '/operacoes/mensagens-whatsapp': typeof OperacoesMensagensWhatsappRoute
  '/conhecimento-cultura': typeof ConhecimentoCulturaIndexRoute
  '/operacoes': typeof OperacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrativo': typeof AdministrativoRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/termos': typeof TermosRoute
  '/conhecimento-cultura/principios': typeof ConhecimentoCulturaPrincipiosRoute
  '/operacoes/contagem-embalagens': typeof OperacoesContagemEmbalagensRoute
  '/operacoes/escala': typeof OperacoesEscalaRoute
  '/operacoes/links-importantes': typeof OperacoesLinksImportantesRoute
  '/operacoes/mensagens-whatsapp': typeof OperacoesMensagensWhatsappRoute
  '/conhecimento-cultura/': typeof ConhecimentoCulturaIndexRoute
  '/operacoes/': typeof OperacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrativo'
    | '/atendimento'
    | '/dashboard'
    | '/termos'
    | '/conhecimento-cultura/principios'
    | '/operacoes/contagem-embalagens'
    | '/operacoes/escala'
    | '/operacoes/links-importantes'
    | '/operacoes/mensagens-whatsapp'
    | '/conhecimento-cultura/'
    | '/operacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrativo'
    | '/atendimento'
    | '/dashboard'
    | '/termos'
    | '/conhecimento-cultura/principios'
    | '/operacoes/contagem-embalagens'
    | '/operacoes/escala'
    | '/operacoes/links-importantes'
    | '/operacoes/mensagens-whatsapp'
    | '/conhecimento-cultura'
    | '/operacoes'
  id:
    | '__root__'
    | '/'
    | '/administrativo'
    | '/atendimento'
    | '/dashboard'
    | '/termos'
    | '/conhecimento-cultura/principios'
    | '/operacoes/contagem-embalagens'
    | '/operacoes/escala'
    | '/operacoes/links-importantes'
    | '/operacoes/mensagens-whatsapp'
    | '/conhecimento-cultura/'
    | '/operacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrativoRoute: typeof AdministrativoRoute
  AtendimentoRoute: typeof AtendimentoRoute
  DashboardRoute: typeof DashboardRoute
  TermosRoute: typeof TermosRoute
  ConhecimentoCulturaPrincipiosRoute: typeof ConhecimentoCulturaPrincipiosRoute
  OperacoesContagemEmbalagensRoute: typeof OperacoesContagemEmbalagensRoute
  OperacoesEscalaRoute: typeof OperacoesEscalaRoute
  OperacoesLinksImportantesRoute: typeof OperacoesLinksImportantesRoute
  OperacoesMensagensWhatsappRoute: typeof OperacoesMensagensWhatsappRoute
  ConhecimentoCulturaIndexRoute: typeof ConhecimentoCulturaIndexRoute
  OperacoesIndexRoute: typeof OperacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativo': {
      id: '/administrativo'
      path: '/administrativo'
      fullPath: '/administrativo'
      preLoaderRoute: typeof AdministrativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/': {
      id: '/operacoes/'
      path: '/operacoes'
      fullPath: '/operacoes/'
      preLoaderRoute: typeof OperacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento-cultura/': {
      id: '/conhecimento-cultura/'
      path: '/conhecimento-cultura'
      fullPath: '/conhecimento-cultura/'
      preLoaderRoute: typeof ConhecimentoCulturaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/mensagens-whatsapp': {
      id: '/operacoes/mensagens-whatsapp'
      path: '/operacoes/mensagens-whatsapp'
      fullPath: '/operacoes/mensagens-whatsapp'
      preLoaderRoute: typeof OperacoesMensagensWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/links-importantes': {
      id: '/operacoes/links-importantes'
      path: '/operacoes/links-importantes'
      fullPath: '/operacoes/links-importantes'
      preLoaderRoute: typeof OperacoesLinksImportantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/escala': {
      id: '/operacoes/escala'
      path: '/operacoes/escala'
      fullPath: '/operacoes/escala'
      preLoaderRoute: typeof OperacoesEscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/contagem-embalagens': {
      id: '/operacoes/contagem-embalagens'
      path: '/operacoes/contagem-embalagens'
      fullPath: '/operacoes/contagem-embalagens'
      preLoaderRoute: typeof OperacoesContagemEmbalagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento-cultura/principios': {
      id: '/conhecimento-cultura/principios'
      path: '/conhecimento-cultura/principios'
      fullPath: '/conhecimento-cultura/principios'
      preLoaderRoute: typeof ConhecimentoCulturaPrincipiosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrativoRoute: AdministrativoRoute,
  AtendimentoRoute: AtendimentoRoute,
  DashboardRoute: DashboardRoute,
  TermosRoute: TermosRoute,
  ConhecimentoCulturaPrincipiosRoute: ConhecimentoCulturaPrincipiosRoute,
  OperacoesContagemEmbalagensRoute: OperacoesContagemEmbalagensRoute,
  OperacoesEscalaRoute: OperacoesEscalaRoute,
  OperacoesLinksImportantesRoute: OperacoesLinksImportantesRoute,
  OperacoesMensagensWhatsappRoute: OperacoesMensagensWhatsappRoute,
  ConhecimentoCulturaIndexRoute: ConhecimentoCulturaIndexRoute,
  OperacoesIndexRoute: OperacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
