begin;

-- =============================================================================
-- Consulta de Estoque backend V1 (Inventory Backend V1) — color dictionary seed
--
-- Depends on 20260909_001 (estoque_cores_mapeamento table).
--
-- Seeds the 419 curated (cor_codigo, cor_descricao_linx) -> portal color
-- mappings from the reviewed source file cores_portal_final.csv. Only the four
-- persistent columns are stored; the source file's produtos_em_estoque /
-- unidades_em_estoque columns are prioritization metadata only and are
-- deliberately NOT persisted (locked decision).
--
-- Mapping key is (cor_codigo, cor_descricao_linx) — the same cor_codigo can
-- legitimately carry multiple Linx source descriptions, so it is never mapped
-- by cor_codigo alone.
--
-- Idempotent: ON CONFLICT refreshes the portal label/family and updated_at so
-- a future environment rebuild (separate dev/prod Supabase) reproduces the same
-- dictionary from this tracked migration rather than an ad hoc CSV import.
-- =============================================================================

insert into public.estoque_cores_mapeamento
  (cor_codigo, cor_descricao_linx, cor_nome_portal, cor_familia)
values
  ('166', 'MARINE', 'Azul-marinho', 'Azul'),
  ('031', 'NOIR', 'Preto', 'Preto'),
  ('001', 'BLANC', 'Branco', 'Branco'),
  ('132', 'VERT', 'Verde', 'Verde'),
  ('240', 'ROUGE', 'Vermelho', 'Vermelho'),
  ('70V', 'FARINE', 'Off-white', 'Branco'),
  ('476', 'BORDEAUX', 'Bordô', 'Vermelho'),
  ('107', 'JAUNE', 'Amarelo', 'Amarelo'),
  ('T01', 'RUISSEAU', 'Azul-claro', 'Azul'),
  ('HBP', 'PANORAMA', 'Azul-claro', 'Azul'),
  ('BMY', 'KAKI', 'Verde-musgo', 'Verde'),
  ('CCA', 'ARGENT CHINE', 'Cinza-mescla', 'Cinza'),
  ('02S', 'VIENNOIS', 'Bege', 'Bege'),
  ('522', 'BLANC/MARINE', 'Branco / Azul-marinho', 'Multicolor'),
  ('57I', 'ARAL', 'Azul-turquesa', 'Azul'),
  ('T03', 'FLAMANT', 'Rosa-flamingo', 'Rosa'),
  ('MKU', 'WASHED BLEACH', 'Jeans claro', 'Azul'),
  ('MK9', 'WASHED DEEP MEDIUM', 'Jeans médio', 'Azul'),
  ('3LA', 'BUFFLE', 'Marrom-couro', 'Marrom'),
  ('HDE', 'ABIMES', 'Azul-marinho', 'Azul'),
  ('ADY', 'NIDUS', 'Rosa-clara', 'Rosa'),
  ('000', 'SANS COLORIS', 'Sem cor', 'Sem cor'),
  ('056', 'NATUREL CLAIR', 'Bege-claro', 'Bege'),
  ('3KE', 'OXALIS', 'Vinho', 'Vermelho'),
  ('3D3', 'GITANE', 'Azul-jeans', 'Azul'),
  ('5AI', 'HONEY', 'Mel', 'Amarelo'),
  ('525', 'MARINE/BLANC', 'Azul-marinho / Branco', 'Multicolor'),
  ('XHU', 'THE', 'Verde-claro', 'Verde'),
  ('F6Z', 'BLANC/PANORAMA', 'Branco / Cinza-claro', 'Multicolor'),
  ('I18', 'LUNE CHINE', 'Bege-mesclado', 'Bege'),
  ('J2G', 'PHOENIX', 'Azul-pastel', 'Cinza'),
  ('000', 'NOIR', 'Preto', 'Preto'),
  ('21G', 'WHT/WHT', 'Branco', 'Branco'),
  ('Z7Z', 'ELECTRIQUE', 'Azul-elétrico', 'Azul'),
  ('BZD', 'EXPRESSO', 'Vinho', 'Vermelho'),
  ('JQ0', 'COBALT', 'Azul-cobalto', 'Azul'),
  ('X6F', 'LIONNE', 'Caramelo', 'Marrom'),
  ('YZP', 'SINOPLE', 'Verde-folha', 'Verde'),
  ('7EZ', 'URBAIN', 'Cinza-urbano', 'Cinza'),
  ('CB8', 'LION', 'Caramelo', 'Marrom'),
  ('RXZ', 'NOIR/BLANC-PLOMB', 'Preto / Branco', 'Multicolor'),
  ('312', 'BLK/WHT', 'Preto / Branco', 'Multicolor'),
  ('E7B', 'PANORAMA/BLANC', 'Cinza-claro / Branco', 'Multicolor'),
  ('5QD', 'DELPHINIUM', 'Azul-lavanda', 'Azul'),
  ('I1L', 'MALVA', 'Malva', 'Rosa'),
  ('2R3', 'RESEDA 07Y', 'Verde-reseda', 'Verde'),
  ('350', 'MERLE', 'Cinza-mescla', 'Cinza'),
  ('HYY', 'BLACK INDIGO', 'Preto-índigo', 'Preto'),
  ('QPT', 'ULTRAMARINE', 'Azul-ultramar', 'Azul'),
  ('JBK', 'ABYSSE', 'Azul-abissal', 'Azul'),
  ('02H', 'BLK/BLK', 'Preto', 'Preto'),
  ('17K', 'RED/WHT', 'Vermelho / Branco', 'Multicolor'),
  ('338', 'BORDEAUX/BLANC', 'Bordô / Branco', 'Multicolor'),
  ('F9F', 'METHYLENE', 'Azul-metileno', 'Azul'),
  ('XFJ', 'LAPONIE', 'Off-white', 'Branco'),
  ('02M', 'MACHE', 'Verde-alface', 'Verde'),
  ('800', 'BLANC/BLANC', 'Branco', 'Branco'),
  ('528', 'ROUGE/MARINE', 'Vermelho / Azul-marinho', 'Multicolor'),
  ('UI2', 'MIAMI', 'Rosa-coral', 'Rosa'),
  ('LDM', 'FLUORINE', 'Verde-flúor', 'Verde'),
  ('1R7', 'GRN/WHT', 'Verde / Branco', 'Multicolor'),
  ('F2W', 'ABIMES/ABIMES', 'Jeans desgastado', 'Azul'),
  ('S5T', 'GRAPHITE', 'Grafite', 'Cinza'),
  ('Z92', 'BLANC/BLANC-BLANC', 'Branco', 'Branco'),
  ('AEY', 'APHYLLA', 'Azul-claro', 'Azul'),
  ('HBM', 'SPHERE', 'Cinza-azulado', 'Cinza'),
  ('SIW', 'CALATHEA', 'Verde-folha', 'Verde'),
  ('1CI', 'MACHE/BOULEAU 10H', 'Verde-alface / Bege-bétula', 'Multicolor'),
  ('RNE', 'RINSE BLUE', 'Azul-escuro', 'Azul'),
  ('361', 'SESAME', 'Bege-gergelim', 'Bege'),
  ('NPA', 'BILLARD', 'Verde-bilhar', 'Verde'),
  ('3GF', 'BLEU INDIGO FONCE', 'Azul-índigo escuro', 'Azul'),
  ('5I1', 'JASI CHINE', 'Azul-mescla', 'Azul'),
  ('802', 'MARINE/VERT', 'Azul-marinho / Verde', 'Multicolor'),
  ('NJ8', 'MUSCARI', 'Azul-violeta', 'Azul'),
  ('2K7', 'LT BLU/WHT', 'Azul-claro / Branco', 'Multicolor'),
  ('SIX', 'COOKIE', 'Marrom-biscoito', 'Marrom'),
  ('ZJ2', 'BLANC/VERT-NOIR', 'Branco / Verde', 'Multicolor'),
  ('37I', 'MACHE/VERT', 'Verde-alface / Verde', 'Verde'),
  ('6BL', 'ALPINES CHINES', 'Cinza-mescla', 'Cinza'),
  ('C31', 'NOIR/NOIR', 'Preto', 'Preto'),
  ('HD9', 'CALCAIRE', 'Bege-pedra', 'Bege'),
  ('HN8', 'VAPOREUX', 'Cinza-vaporoso', 'Cinza'),
  ('4JW', 'CAVALIERE CHINE', 'Cinza-mescla', 'Cinza'),
  ('I1K', 'PISTE', 'Bege-claro', 'Bege'),
  ('MR8', 'RUISSEAU/BLANC', 'Azul-acinzentado / Branco', 'Multicolor'),
  ('HJM', 'LAZULI', 'Azul-lápis-lazúli', 'Azul'),
  ('MNC', 'ARGENT CHINE/MARINE', 'Cinza-mescla / Azul-marinho', 'Multicolor'),
  ('N6I', 'MANSIA', 'Verde-acinzentado', 'Verde'),
  ('Z4H', 'ALBIZIA', 'Rosa-claro', 'Rosa'),
  ('141', 'PENOMBRE', 'Cinza-penumbra', 'Cinza'),
  ('454', 'BLK/OFF WHT', 'Preto / Off-white', 'Multicolor'),
  ('49Y', 'APHYLLA/PHOENIX', 'Verde-acinzentado / Cinza-chumbo', 'Multicolor'),
  ('7PL', 'VARECH FONCE/BLANC', 'Marrom-alga / Branco', 'Multicolor'),
  ('9LM', 'MEDIUM INDIGO WASH', 'Jeans médio', 'Azul'),
  ('AFS', 'IBERIS', 'Vermelho telha', 'Vermelho'),
  ('2QB', 'TURQUIN/BLANC', 'Azul-turquim / Branco', 'Multicolor'),
  ('737', 'BLANC/VERT', 'Branco / Verde', 'Multicolor'),
  ('HCF', 'ESCADRON', 'Azul-esquadrão', 'Azul'),
  ('HHW', 'MARINE/FARINE', 'Azul-marinho / Off-white', 'Multicolor'),
  ('HLU', 'BALNEAIRE', 'Azul-piscina', 'Azul'),
  ('JCH', 'ZINNIA', 'Rosa-zínia', 'Rosa'),
  ('ML4', 'WASHED RINSE', 'Jeans lavado', 'Azul'),
  ('S1B', 'THE/THYM', 'Chá (marrom-claro) / Verde-tomilho', 'Multicolor'),
  ('SPI', 'ANSE', 'Azul-baía', 'Azul'),
  ('SQI', 'SPINELLE', 'Rosa-fúcsia', 'Rosa'),
  ('06C', 'OFF WHT/PNK', 'Off-white / Rosa', 'Multicolor'),
  ('092', 'NVY/WHT', 'Azul-marinho / Branco', 'Multicolor'),
  ('14X', 'WHT/LT GRY', 'Branco / Cinza-claro', 'Multicolor'),
  ('67G', 'CRATERE', 'Cinza-crater', 'Cinza'),
  ('8VM', 'NOIR/NOIR-NOIR', 'Preto', 'Preto'),
  ('964', 'NOIR/VERT', 'Preto / Verde', 'Multicolor'),
  ('1S6', 'WHT/DK PURP', 'Branco / Roxo-escuro', 'Multicolor'),
  ('7FD', 'BLANC/NIDUS', 'Branco / Bege-areia', 'Multicolor'),
  ('AS3', 'OFF BLK/OFF WHT', 'Preto-fumê / Off-white', 'Multicolor'),
  ('F50', 'PNK/WHT', 'Rosa / Branco', 'Multicolor'),
  ('I4U', 'ARGENTINE/MARINE', 'Cinza-argênteo / Azul-marinho', 'Multicolor'),
  ('LGF', 'PASTILLE', 'Rosa-pastilha', 'Rosa'),
  ('PT3', 'LT PNK/LT TAN', 'Rosa-claro / Bege-claro', 'Multicolor'),
  ('SFI', 'CERISIER', 'Vermelho-cereja', 'Vermelho'),
  ('TAM', 'ARAL/URBAIN', 'Azul-turquesa / Cinza-urbano', 'Multicolor'),
  ('ZBG', 'GRENADINE', 'Rosa-grená', 'Rosa'),
  ('206', 'LT GRY/LT BLU', 'Cinza-claro / Azul-claro', 'Multicolor'),
  ('291', 'VERT/BLANC', 'Verde / Branco', 'Multicolor'),
  ('4EI', 'BILLARD 05H/JAUNE', 'Verde-amarelado', 'Verde'),
  ('4XA', 'ARGENTINE', 'Cinza-argênteo', 'Cinza'),
  ('4ZI', 'VERT/BOULEAU 10H', 'Verde / Bege-bétula', 'Multicolor'),
  ('BVG', 'LITTORAL', 'Azul-litoral', 'Azul'),
  ('C4X', 'BLEU FRANCE', 'Azul-frança', 'Azul'),
  ('C7T', 'PISTIL', 'Amarelo-pistilo', 'Amarelo'),
  ('E8G', 'ECLIPSE JASPE', 'Cinza-jaspe', 'Cinza'),
  ('GFU', 'NEVA', 'Azul-neva', 'Azul'),
  ('IZY', 'ROSE DYED', 'Rosa tingido', 'Rosa'),
  ('J18', 'NVY/OFF WHT', 'Azul-marinho / Off-white', 'Multicolor'),
  ('SI0', 'OCELLE', 'Cinza-oceleado', 'Cinza'),
  ('0VZ', 'ASH', 'Cinza-cendra', 'Cinza'),
  ('2D2', 'DK GRN/WHT', 'Verde-escuro / Branco', 'Multicolor'),
  ('463', 'NOIR/APHYLLA', 'Preto / Verde-acinzentado', 'Multicolor'),
  ('4PW', 'GEMME', 'Verde-gema', 'Verde'),
  ('6XP', 'NAPOLITAIN', 'Rosa-napolitano', 'Rosa'),
  ('IC3', 'KAKI/MULTICO', 'Caqui / Multicolorido', 'Multicolor'),
  ('QRN', 'MARINE/MULTICO', 'Azul-marinho / Multicolorido', 'Multicolor'),
  ('SKB', 'PORTO 0', 'Vinho do Porto', 'Vermelho'),
  ('SQZ', 'BLANC/PHOENIX-LAUZE', 'Branco / Cinza-chumbo', 'Multicolor'),
  ('VY0', 'NATUREL CLAIR/SISAL', 'Bege-claro / Bege-sisal', 'Bege'),
  ('W34', 'MARINE/ARGENT CHINE-ROUGE', 'Azul-marinho / Cinza-mescla', 'Multicolor'),
  ('WAL', 'CORVETTE', 'Azul-corvette', 'Azul'),
  ('1GF', 'BLEU INDIGO CLAIR', 'Azul-índigo claro', 'Azul'),
  ('1U2', 'WHT/ORG', 'Branco / Laranja', 'Multicolor'),
  ('1Y5', 'OFF WHT/DK GRN', 'Off-white / Verde-escuro', 'Multicolor'),
  ('3N8', 'RESEDA/BLANC', 'Verde-reseda / Branco', 'Multicolor'),
  ('6SY', 'ELEPHANT', 'Cinza-elefante', 'Cinza'),
  ('BW7', 'LT BRW/OFF WHT', 'Marrom-claro / Off-white', 'Multicolor'),
  ('CNQ', 'ROQUETTE', 'Verde-rúcula', 'Verde'),
  ('E9F', 'OLIVE 06Y', 'Verde-oliva', 'Verde'),
  ('GG2', 'GRN/GRN', 'Verde', 'Verde'),
  ('IPQ', 'PHOENIX/MULTICO', 'Cinza-chumbo / Multicolorido', 'Multicolor'),
  ('IY2', 'MAUVEGLOW', 'Rosa-malva', 'Rosa'),
  ('IY4', 'HYDRO', 'Azul-hidro', 'Azul'),
  ('L99', 'AERIEN', 'Azul-aéreo', 'Azul'),
  ('TTF', 'LIAMONE', 'Verde-liamone', 'Verde'),
  ('WB3', 'MARINE/PHOENIX', 'Azul-marinho / Cinza-chumbo', 'Multicolor'),
  ('ZIH', 'LATTE', 'Bege-latte', 'Bege'),
  ('021', 'MARINE 166', 'Azul-marinho', 'Azul'),
  ('031', 'DK BRW/GUM', 'Marrom-escuro / Bege-borracha', 'Multicolor'),
  ('082', 'WHT/GRN', 'Branco / Verde', 'Multicolor'),
  ('2G9', 'OFF WHT/BLK', 'Off-white / Preto', 'Multicolor'),
  ('2P2', 'DK GRY/GRY', 'Cinza-escuro / Cinza', 'Cinza'),
  ('8XF', 'MILLET', 'Amarelo-milho', 'Amarelo'),
  ('A4A', 'MARINE/ABYSSE', 'Azul-marinho / Azul-abissal', 'Azul'),
  ('ACZ', 'CALLUNA', 'Roxo-calluna', 'Roxo'),
  ('AHP', 'MARINE/BLANC-NOIR', 'Azul-marinho / Branco', 'Multicolor'),
  ('AI4', 'ARGENT CHINE/SINOPLE-NOIR', 'Cinza-mescla / Verde-musgo', 'Multicolor'),
  ('FWN', 'CORSE', 'Verde-corso', 'Verde'),
  ('GBX', 'PANORAMA/VERT', 'Cinza-claro / Verde', 'Multicolor'),
  ('I17', 'FRAISE CHINE', 'Rosa-morango mescla', 'Rosa'),
  ('I5P', 'BRASILIA/ARGENTINE', 'Azul-brasília / Cinza-argênteo', 'Multicolor'),
  ('KF9', 'NYMPHEA', 'Rosa-ninféia', 'Rosa'),
  ('M62', 'MONO FARINE ZIN', 'Off-white', 'Branco'),
  ('NRE', 'SERINGAT', 'Branco-seringueira', 'Branco'),
  ('NWR', 'NVY/WHT/DK RED', 'Azul-marinho / Branco / Vermelho-escuro', 'Multicolor'),
  ('T33', 'MILLET', 'Amarelo-milho', 'Amarelo'),
  ('ZBA', 'FIDJI', 'Azul-fiji', 'Azul'),
  ('075', 'BLK/NVY', 'Preto / Azul-marinho', 'Multicolor'),
  ('1TB', 'BLANC/RUISSEAU', 'Branco / Azul-acinzentado', 'Multicolor'),
  ('316', 'TANK', 'Verde-militar', 'Verde'),
  ('6JE', 'FARINE/DELPHINIUM', 'Off-white / Azul-lavanda', 'Multicolor'),
  ('79', 'AZUL MARINO', 'Azul-marinho', 'Azul'),
  ('7PM', 'BLANC/APHYLLA', 'Branco / Verde-acinzentado', 'Multicolor'),
  ('7XI', 'MERLE/FARINE', 'Cinza-mescla / Off-white', 'Multicolor'),
  ('DHI', 'BLANC/FLAMANT', 'Branco / Rosa-flamingo', 'Multicolor'),
  ('EL8', 'PIN JASPE', 'Rosa-jaspe', 'Rosa'),
  ('GN1', 'GRN/NVY', 'Verde / Azul-marinho', 'Multicolor'),
  ('IXA', 'CRIQUE CHINE', 'Cinza-mescla', 'Cinza'),
  ('KC8', 'PLATINE', 'Cinza-platina', 'Cinza'),
  ('KXB', 'ROYAUME', 'Azul-royal', 'Azul'),
  ('MXQ', 'MARINE SOMBRE', 'Azul-marinho escuro', 'Azul'),
  ('Q17', 'CLARET RED', 'Vermelho-clarete', 'Vermelho'),
  ('SJ1', 'ARGENT CHINE/NOIR-BLANC', 'Cinza-mescla / Preto', 'Multicolor'),
  ('TS1', 'LT BLU/OFF WHT', 'Azul-claro / Off-white', 'Multicolor'),
  ('WKE', 'MARINE SOMBRE/FARINE-HONE', 'Azul-marinho escuro / Off-white', 'Multicolor'),
  ('Z13', 'BLANC/URBAIN', 'Branco / Cinza-urbano', 'Multicolor'),
  ('12I', 'POUDRE/MERLE', 'Rosa-pó / Cinza-mescla', 'Multicolor'),
  ('1RR', 'MILLET/FARINE', 'Amarelo-milho / Off-white', 'Multicolor'),
  ('221', 'BLU/WHT', 'Azul / Branco', 'Multicolor'),
  ('2I7', 'MERLE/POUDRE', 'Cinza-mescla / Rosa-pó', 'Multicolor'),
  ('2S3', 'NVY/GRN', 'Azul-marinho / Verde', 'Multicolor'),
  ('381', 'VERT/MARINE', 'Verde / Azul-marinho', 'Multicolor'),
  ('3RR', 'LAPONIE/LIONNE', 'Azul-caramelo', 'Azul'),
  ('3WI', 'MACHE/BOULEAU 10H-BLANC-N', 'Verde-alface / Bege-bétula', 'Multicolor'),
  ('4KF', 'FARINE/VIENNOIS', 'Off-white / Bege-rosado', 'Multicolor'),
  ('6J7', 'NIDUS/CORVETTE-BLANC', 'Bege-areia / Azul-corvette', 'Multicolor'),
  ('6NM', 'BLACK WASHED', 'Preto lavado', 'Preto'),
  ('6XH', 'NOIR/LAPONIE-SINOPLE', 'Preto / Azul-gelo', 'Multicolor'),
  ('7B4', 'NVY/DK GRN', 'Azul-marinho / Verde-escuro', 'Multicolor'),
  ('C87', 'VIENNOIS', 'Bege-rosado', 'Bege'),
  ('FAC', 'BLANC/RUISSEAU', 'Branco / Azul-acinzentado', 'Multicolor'),
  ('HH7', 'AERIEN/BLANC', 'Azul-aéreo / Branco', 'Multicolor'),
  ('IXQ', 'CROISSANT', 'Bege-croissant', 'Bege'),
  ('KBR', 'NOIR/MULTICO', 'Preto / Multicolorido', 'Multicolor'),
  ('KZA', 'MARINE/ARGENT CHINE', 'Azul-marinho / Cinza-mescla', 'Multicolor'),
  ('LRR', 'RUBINE/BLANC', 'Vermelho-rubi / Branco', 'Multicolor'),
  ('M66', 'NOIR FARINE', 'Preto / Off-white', 'Multicolor'),
  ('MK2', 'WASHED LIGHT GREY', 'Cinza-claro lavado', 'Cinza'),
  ('NPB', 'MANDARINIER 08E', 'Laranja-tangerina', 'Laranja'),
  ('NV1', 'NVY/BLU', 'Azul-marinho / Azul', 'Azul'),
  ('W4I', 'RESEDA 07Y/VERT', 'Verde-reseda / Verde', 'Verde'),
  ('WKZ', 'SINOPLE/FARINE-MANSIA', 'Verde-musgo / Off-white', 'Multicolor'),
  ('0RI', 'EXPRESSO/BLOSSOM-FARINE', 'Marrom-café / Rosa-flor', 'Multicolor'),
  ('18C', 'OFF WHT/OFF WHT', 'Off-white', 'Branco'),
  ('1R5', 'WHT/DK GRN', 'Branco / Verde-escuro', 'Multicolor'),
  ('2R2', 'OFF WHT/LT BRW', 'Off-white / Marrom-claro', 'Multicolor'),
  ('4CI', 'MERLE/GRAPHITE', 'Cinza-mescla / Grafite', 'Cinza'),
  ('65T', 'WHT/OFF WHT', 'Branco / Off-white', 'Branco'),
  ('6AI', 'BLEU FRANCE/VERT', 'Azul-frança / Verde', 'Multicolor'),
  ('6JG', 'BIGARREAU/VERT', 'Vermelho-cereja / Verde', 'Multicolor'),
  ('6JM', 'OLIVE 06Y/BLEU FRANCE', 'Verde-oliva / Azul-frança', 'Multicolor'),
  ('6KI', 'VIENNOIS/DELPHINIUM', 'Bege-rosado / Azul-lavanda', 'Multicolor'),
  ('7B4', 'NVY/GRN', 'Azul-marinho / Verde', 'Multicolor'),
  ('9IX', 'SINOPLE/JAUNE-VERT-BLANC/', 'Multicolorido', 'Multicolor'),
  ('9N5', 'APHYLLA/MARINE', 'Verde-acinzentado / Azul-marinho', 'Multicolor'),
  ('AIG', 'SINOPLE/FARINE-NIDUS', 'Verde-musgo / Off-white', 'Multicolor'),
  ('B53', 'WHT/PNK', 'Branco / Rosa', 'Multicolor'),
  ('BDM', 'COSMIQUE', 'Azul-cósmico', 'Azul'),
  ('CQK', 'GRAND BLEU', 'Azul-profundo', 'Azul'),
  ('DB3', 'MARINE/ROUGE-BLANC', 'Azul-marinho / Vermelho', 'Multicolor'),
  ('F5T', 'BAILLOUX', 'Marrom-bailloux', 'Marrom'),
  ('F8R', 'AQUARIUM 07H', 'Azul-aquário', 'Azul'),
  ('FLN', 'PASTIS', 'Verde-pastis', 'Verde'),
  ('FY8', 'LASER', 'Verde-laser', 'Verde'),
  ('HBI', 'LAPONIE/IBERIS-PISTE', 'Azul-gelo / Rosa-iberis', 'Multicolor'),
  ('I5Q', 'ZINNIA/ARGENTINE', 'Rosa-zínia / Cinza-argênteo', 'Multicolor'),
  ('IXW', 'LADIGUE', 'Azul-ladigue', 'Azul'),
  ('IY1', 'CORNSILK', 'Amarelo-claro', 'Amarelo'),
  ('P40', 'BOUEE', 'Laranja-bóia', 'Laranja'),
  ('PQS', 'FRIANDISE', 'Rosa-doce', 'Rosa'),
  ('PTV', 'IBIZA', 'Azul-ibiza', 'Azul'),
  ('QKI', 'CALATHEA/MULTICO', 'Verde-folha / Multicolorido', 'Multicolor'),
  ('R1I', 'MARINE/ZIN', 'Azul-marinho / Amarelo-zin', 'Multicolor'),
  ('S86', 'THYM', 'Verde-tomilho', 'Verde'),
  ('SGI', 'BARDANE', 'Verde-bardana', 'Verde'),
  ('SIY', 'HILO', 'Azul-hilo', 'Azul'),
  ('TTV', 'BRASILIA', 'Azul-brasília', 'Azul'),
  ('VPP', 'FARINE/RUISSEAU-SINOPLE', 'Off-white / Azul-acinzentado', 'Multicolor'),
  ('WP2', 'OFF WHT/LT GRN', 'Off-white / Verde-claro', 'Multicolor'),
  ('X67', 'BLANC/MARINE-BOURGOGNE', 'Branco / Azul-marinho', 'Multicolor'),
  ('XA4', 'ATOLL', 'Azul-atol', 'Azul'),
  ('XE4', 'SINOPLE/MARINE SOMBRE-FAR', 'Verde-musgo / Azul-marinho escuro', 'Multicolor'),
  ('XI7', 'MANSIA/SINOPLE-FARINE', 'Verde-acinzentado / Verde-musgo', 'Verde'),
  ('YUP', 'ZIN', 'Amarelo-zin', 'Amarelo'),
  ('Z1W', 'NOIR/PATISSON', 'Preto / Amarelo-patisson', 'Multicolor'),
  ('ZV9', 'SIERRA', 'Marrom-serra', 'Marrom'),
  ('01U', 'GRN/OFF WHT', 'Verde / Off-white', 'Multicolor'),
  ('03', 'GRIS', 'Cinza', 'Cinza'),
  ('0SI', 'MILLET/NATUREL CLAIR', 'Amarelo-milho / Bege-claro', 'Multicolor'),
  ('121', 'DK BLU/WHT', 'Azul-escuro / Branco', 'Multicolor'),
  ('1IG', 'JAUNE/BILLARD', 'Amarelo / Verde-bilhar', 'Multicolor'),
  ('25Y', 'GRY/WHT', 'Cinza / Branco', 'Multicolor'),
  ('2B7', 'OFF WHT/GRY', 'Off-white / Cinza', 'Multicolor'),
  ('2H4', 'WHT/KHK', 'Branco / Caqui', 'Multicolor'),
  ('4JM', 'PIEUVRE CHINE', 'Cinza-mescla', 'Cinza'),
  ('4JS', 'MURENE CHINE', 'Cinza-mescla', 'Cinza'),
  ('6S8', 'BLUE RINSE', 'Azul lavado', 'Azul'),
  ('709', 'BARBEAU', 'Azul-centáurea', 'Azul'),
  ('883', 'HAUT ROUGE', 'Vermelho-intenso', 'Vermelho'),
  ('9QA', 'CLUSI CHINE', 'Cinza-mescla', 'Cinza'),
  ('ABX', 'ORG/GUM', 'Laranja / Bege-borracha', 'Multicolor'),
  ('AN6', 'WHT/NVY/PNK', 'Branco / Azul-marinho / Rosa', 'Multicolor'),
  ('APF', 'ESTIVAL', 'Bege-estival', 'Bege'),
  ('APH', 'ORG/DK ORG', 'Laranja', 'Laranja'),
  ('AU8', 'BLANC/NOIR', 'Branco / Preto', 'Multicolor'),
  ('BSH', 'LAQUE', 'Vermelho-laca', 'Vermelho'),
  ('BW8', 'LT BRW/WHT', 'Marrom-claro / Branco', 'Multicolor'),
  ('CUN', 'CALCAIRE/FAUCON', 'Bege-pedra / Marrom-falcão', 'Multicolor'),
  ('D4J', 'HORIZON 06Y', 'Amarelo-horizonte', 'Amarelo'),
  ('D6Z', 'FARINE/RUISSEAU', 'Off-white / Azul-acinzentado', 'Multicolor'),
  ('EV0', 'FARINE/MARINE', 'Off-white / Azul-marinho', 'Multicolor'),
  ('F8M', 'GROSEILLIER', 'Vermelho-groselha', 'Vermelho'),
  ('FKP', 'ORANGERAIE', 'Laranja', 'Laranja'),
  ('FXJ', 'AQUA', 'Azul-água', 'Azul'),
  ('HAU', 'NEBULEUSE CHINE', 'Cinza-mescla', 'Cinza'),
  ('IFX', 'SIERRA DYED', 'Marrom tingido', 'Marrom'),
  ('IHJ', 'PHOENIX/FARINE-MARINE', 'Cinza-chumbo / Off-white', 'Multicolor'),
  ('IUU', 'LADIGUE/MARINE', 'Azul-ladigue / Azul-marinho', 'Azul'),
  ('IXU', 'OSEILLE', 'Verde-azedinha', 'Verde'),
  ('JI5', 'LIMEIRA/ANSE-FARINE', 'Verde-limão / Azul-baía', 'Multicolor'),
  ('JIX', 'PANORAMA/FARINE-VERT', 'Cinza-claro / Off-white', 'Multicolor'),
  ('KC9', 'THERMES CHINE', 'Cinza-mescla', 'Cinza'),
  ('L24', 'ABIMES', 'Jeans desgastado', 'Azul'),
  ('L69', 'CIMENT FLORIDE NOIR', 'Preto-cimento', 'Preto'),
  ('N16', 'BLOSSOM', 'Rosa-flor', 'Rosa'),
  ('N81', 'TAUPE', 'Taupe', 'Marrom'),
  ('NI8', 'OCELLE/ZIN', 'Cinza-oceleado / Amarelo-zin', 'Multicolor'),
  ('NUA', 'NOIR/BLANC-ARGENT CHINE', 'Preto / Branco', 'Multicolor'),
  ('P0Y', 'NIMBUS', 'Cinza-nimbo', 'Cinza'),
  ('QDS', 'TOURMALINE', 'Verde-turmalina', 'Verde'),
  ('R92', 'DARK MARBLE GREY', 'Cinza-mármore escuro', 'Cinza'),
  ('S7T', 'BAOBAB', 'Marrom-baobá', 'Marrom'),
  ('T36', 'VIENNOIS SOJA', 'Bege-soja', 'Bege'),
  ('T38', 'PHOENIX TURQUIN', 'Azul-turquim', 'Azul'),
  ('UYB', 'BOULEAU 10H', 'Bege-bétula', 'Bege'),
  ('X1J', 'PHOENIX/MARINE', 'Cinza-chumbo / Azul-marinho', 'Multicolor'),
  ('003', 'NAVY', 'Azul-marinho', 'Azul'),
  ('02', 'NEGRO', 'Preto', 'Preto'),
  ('042', 'WHT/NVY', 'Branco / Azul-marinho', 'Multicolor'),
  ('092', 'NAVY/WHITE', 'Azul-marinho / Branco', 'Multicolor'),
  ('1PW', 'IODE/NOIR', 'Marrom-iodo / Preto', 'Multicolor'),
  ('1R6', 'BLK/DK GRN', 'Preto / Verde-escuro', 'Multicolor'),
  ('222', 'WHITE/DARK RED/NAVY', 'Branco / Vermelho-escuro / Azul-marinho', 'Multicolor'),
  ('2E2', 'DARK BROWN/BROWN', 'Marrom-escuro / Marrom', 'Marrom'),
  ('2M1', 'DK GRY/OFF WHT', 'Cinza-escuro / Off-white', 'Multicolor'),
  ('3DH', 'FORAINE', 'Rosa-forana', 'Rosa'),
  ('3E8', 'LT TAN/BLK', 'Bege-claro / Preto', 'Multicolor'),
  ('3H6', 'NAUTIQUE', 'Azul-náutico', 'Azul'),
  ('3UI', 'MARINE/CHAMBRAY-FARINE', 'Azul-marinho / Azul-chambray', 'Azul'),
  ('423', 'MARINE/MARINE', 'Azul-marinho', 'Azul'),
  ('54', 'SUELA', 'Marrom-sola', 'Marrom'),
  ('5SX', 'COCCINELLE', 'Vermelho-joaninha', 'Vermelho'),
  ('6FW', 'DAPHNE', 'Rosa-dáfne', 'Rosa'),
  ('6IS', 'LAPONIE/THYM', 'Azul-gelo / Verde-tomilho', 'Multicolor'),
  ('6SS', 'FLAMANT/VERT', 'Rosa-flamingo / Verde', 'Multicolor'),
  ('6VT', 'NOIR/LIMEIRA', 'Preto / Verde-limão', 'Multicolor'),
  ('6WZ', 'MARINE/FARINE-VERMOUTH', 'Azul-marinho / Off-white', 'Multicolor'),
  ('70', 'MARRON', 'Marrom', 'Marrom'),
  ('776', 'TURQUIN', 'Azul-turquim', 'Azul'),
  ('78X', 'SCILLE', 'Azul-esquila', 'Azul'),
  ('8AU', 'BLANC/GOLD-GOLD', 'Branco / Dourado', 'Multicolor'),
  ('95K', 'NAVY/NAVY', 'Azul-marinho', 'Azul'),
  ('992', 'MARINE 166', 'Azul-marinho', 'Azul'),
  ('AE0', 'MINOR', 'Azul-minor', 'Azul'),
  ('AI6', 'FARINE/OLIVE 06Y-SESAME', 'Off-white / Verde-oliva', 'Multicolor'),
  ('B50', 'MARINE 166 ROUGE 240', 'Azul-marinho / Vermelho', 'Multicolor'),
  ('B9U', 'ROYALE', 'Azul-royal', 'Azul'),
  ('BCL', 'TURQUOISE', 'Azul-turquesa', 'Azul'),
  ('BLM', 'CITRON', 'Amarelo-limão', 'Amarelo'),
  ('C7Z', 'FAUCON', 'Marrom-falcão', 'Marrom'),
  ('C9', 'NEGRO/AZUL MARINO', 'Preto / Azul-marinho', 'Multicolor'),
  ('CAB', 'CHLOROPHYLLE', 'Verde-clorofila', 'Verde'),
  ('CPI', 'FARINE/CALCAIRE', 'Off-white / Bege-pedra', 'Multicolor'),
  ('CPM', 'CHAIR', 'Nude', 'Bege'),
  ('D99', 'ARGENTINE/FARINE', 'Cinza-argênteo / Off-white', 'Multicolor'),
  ('DB2', 'DK BRW/DK BRW', 'Marrom-escuro', 'Marrom'),
  ('DIK', 'RUISSEAU/GITANE', 'Azul-acinzentado / Vinho', 'Multicolor'),
  ('E76', 'ACONIT', 'Roxo-acônito', 'Roxo'),
  ('F8U', 'BERMUDES 08E', 'Azul-bermudas', 'Azul'),
  ('F9C', 'AMARYLLIS', 'Vermelho-amarílis', 'Vermelho'),
  ('G45', 'ABIMES/FARINE', 'Jeans desgastado / Off-white', 'Multicolor'),
  ('G5K', 'EDEN', 'Verde-éden', 'Verde'),
  ('G6K', 'BOCAGE', 'Verde-bosque', 'Verde'),
  ('GWI', 'MARINE/RUISSEAU-GRENADINE', 'Azul-marinho / Azul-acinzentado', 'Azul'),
  ('HDB', 'RECIF', 'Azul-recife', 'Azul'),
  ('HLL', 'LUPIN', 'Roxo-lupino', 'Roxo'),
  ('HY0', 'MARINE/VERT-ROUGE-MARINE', 'Azul-marinho / Verde', 'Multicolor'),
  ('I0J', 'FAUCON/CALCAIRE', 'Marrom-falcão / Bege-pedra', 'Multicolor'),
  ('I0M', 'MARINE/CALCAIRE-RUISSEAU', 'Azul-marinho / Bege-pedra', 'Multicolor'),
  ('IGJ', 'SIERRA/SPHERE', 'Marrom-serra / Cinza-azulado', 'Multicolor'),
  ('IGY', 'FARINE/SPLEEN-ROUGE', 'Off-white / Vermelho', 'Multicolor'),
  ('IKH', 'NOIR/CROISSANT-FARINE', 'Preto / Bege-croissant', 'Multicolor'),
  ('IU1', 'LADIGUE/MULTICO', 'Azul-ladigue / Multicolorido', 'Multicolor'),
  ('IUV', 'MARINE/LADIGUE', 'Azul-marinho / Azul-ladigue', 'Azul'),
  ('IXV', 'GELATO', 'Rosa-gelato', 'Rosa'),
  ('IY3', 'BONNIE', 'Rosa-bonnie', 'Rosa'),
  ('IZV', 'PASTILLE DYED', 'Rosa tingido', 'Rosa'),
  ('IZX', 'BEIGE DYED', 'Bege tingido', 'Bege'),
  ('J18', 'NAVY/OFFWHITE', 'Azul-marinho / Off-white', 'Multicolor'),
  ('K1Q', 'MARINA', 'Azul-marina', 'Azul'),
  ('LFA', 'PECAN', 'Marrom-pecã', 'Marrom'),
  ('LY2', 'LT YLW/LT YLW', 'Amarelo-claro', 'Amarelo'),
  ('M36', 'ZIN', 'Amarelo-zin', 'Amarelo'),
  ('N0Z', 'BLANC/SILVER', 'Branco / Prata', 'Multicolor'),
  ('NU1', 'PEACH', 'Rosa-pêssego', 'Rosa'),
  ('P00', 'NOIR', 'Preto', 'Preto'),
  ('PFN', 'SAMUI', 'Azul-samui', 'Azul'),
  ('PHD', 'REVOLUTION CHINE', 'Cinza-mescla', 'Cinza'),
  ('Q19', 'ABIMES PETUNIA', 'Rosa-desgastado', 'Rosa'),
  ('QIE', 'METHYLENE/FARINE', 'Azul-metileno / Off-white', 'Multicolor'),
  ('QKA', 'AQUAMARINE', 'Azul-aquamarine', 'Azul'),
  ('QMN', 'CERFEUIL', 'Verde-cerefólio', 'Verde'),
  ('QMR', 'MARQUISES', 'Azul-marquesas', 'Azul'),
  ('S5M', 'OLYMPE', 'Roxo-olimpo', 'Roxo'),
  ('S6T', 'MAREE 1', 'Azul-maré', 'Azul'),
  ('SIZ', 'AGRION', 'Azul-libélula', 'Azul'),
  ('SJI', 'SUNRISE', 'Laranja-nascer do sol', 'Laranja'),
  ('SLI', 'LUCIOLE', 'Amarelo-vagalume', 'Amarelo'),
  ('SMI', 'SEQUOIA', 'Marrom-sequoia', 'Marrom'),
  ('TUK', 'LIMEIRA', 'Verde-limão', 'Verde'),
  ('UH1', 'OFF WHT/LT PNK', 'Off-white / Rosa-claro', 'Multicolor'),
  ('US5', 'MARINIERE', 'Azul-marinheiro', 'Azul'),
  ('UYX', 'PEPPERMINT', 'Verde-menta', 'Verde'),
  ('W15', 'ANTILLES', 'Azul-antilhas', 'Azul'),
  ('WG1', 'OFF WHITE/GREEN', 'Off-white / Verde', 'Multicolor'),
  ('X0U', 'CAPITAINE', 'Azul-capitão', 'Azul'),
  ('X47', 'IRRESISTIBLE', 'Vermelho-irresistível', 'Vermelho'),
  ('XG4', 'FARINE/ROUGE', 'Off-white / Vermelho', 'Multicolor'),
  ('Y05', 'WHT/LT TAN', 'Branco / Bege-claro', 'Multicolor'),
  ('YB2', 'YLW/BLK', 'Amarelo / Preto', 'Multicolor'),
  ('YRR', 'VERT/FARINE', 'Verde / Off-white', 'Multicolor'),
  ('Z6T', 'CITROUILLE', 'Laranja-abóbora', 'Laranja'),
  ('Z7F', 'PINOT', 'Vinho', 'Vermelho')
on conflict (cor_codigo, cor_descricao_linx) do update set
  cor_nome_portal = excluded.cor_nome_portal,
  cor_familia = excluded.cor_familia,
  updated_at = now();

do $$
declare
  v_count integer;
begin
  select count(*) into v_count from public.estoque_cores_mapeamento;
  if v_count <> 419 then
    raise exception 'estoque_cores_mapeamento seed expected 419 rows, found %', v_count;
  end if;
end $$;

commit;
